### ISSUE TITLE
pipe support

### ISSUE THREAD

**Issue by dch** [zalora/zerobin#1]
I love this, super easy to give to people to use. Is it possible to add unix pipe support? `cat foo | zerobin` would allow sending stuff direct from terminal to zerobin without a temporary file.

**Comment by ip1981** [comment]
Why not :-)

Here is a workaround:

```
zerobin "$(cat foo)"
```

**Comment by ip1981** [comment]
Would `zerobin -f -` be ok?

**Comment by dch** [comment]
I've been using `zerobin ' <paste all the things>'` as a workaround, but `-f -` would be perfect - maximum  pipeability!

**Comment by ip1981** [comment]
Done in [1.5.1](http://hackage.haskell.org/package/zerobin-1.5.1)

Commit: https://github.com/zalora/zerobin/commit/718a348afaf6a78a0f0074330d03ac410f487a50
